---
# sequance of execution 

- name: webserver installtion n configuration
  hosts: webservers
  remote_user: root

  roles:
    - web

- name: application server installtion n configuration
  hosts: appservers
  remote_user: root

  roles:
    - app

