---

   - name: Create Installer Directory 
     file: path={{ installer_dir }} owner=hybris group=hybris mode=0644 state=directory

   - name: Download java 
     get_url: url={{ repo }}/Hybris/jdk-{{ java_version }}.zip dest={{ installer_dir }}  mode=0440 

   - name: Download Hybris 
     get_url: url={{ repo }}/Hybris/hybris-commerce-suite-{{ hybris_version }}.zip dest={{ installer_dir }}  mode=0440

   - name: Download oracle Jar
     get_url: url={{ repo }}/Hybris/ojdbc7.zip dest={{ installer_dir }} mode=0440

   - name: Download hybris License 
     get_url: url={{ repo }}/Hybris/hybrislicence.jar dest={{ installer_dir }} mode=0440
      
   - name: Install Java
     command: chdir={{ installer_dir }} /usr/bin/unzip -o jdk-{{ java_version }}.zip -d {{ application_home }}

   - name: Symlink install directory jdk
     file: src={{ application_home }}/jdk-{{ java_version }} path={{ application_home }}/jdk state=link

   - name: set JAVA_HOME environment variable
     action: lineinfile dest=~/.bash_profile regexp='export JAVA_HOME.*' line='export JAVA_HOME={{ application_home }}/jdk'

   - name: Install Hybris
     command: chdir={{ installer_dir }} /usr/bin/unzip -o hybris-commerce-suite-{{ hybris_version }}.zip  'hybris/*' -d {{ application_home }}/hybris-{{ hybris_version }} 

   - name: Symlink install directory hybris
     file: src={{ application_home }}/hybris-{{ hybris_version }} path={{ application_home }}/hybris state=link


   - name: Hybris Configuration | ant clean all
     shell: . ./setantenv.sh && ant clean all -Dinput.template={{ mode }}  -DJAVAMEM=3G chdir={{ application_home }}/hybris/hybris/bin/platform



   - name: Install Hybris license
     command: chdir={{ installer_dir }} /usr/bin/cp -r hybrislicence.jar  {{ application_home }}/hybris/hybris/config/licence/hybrislicence.jar 
     register: cat 
   - debug: var=cat.stdout_lines

   - name: Install Oracle jar 
     command: chdir={{ installer_dir }} /usr/bin/unzip -o ojdbc7.zip -d {{ application_home }}/hybris/hybris/bin/platform/lib/dbdriver/

   - name: Change ownership of Tomcat installation
     file: path={{ application_home }} owner={{ application_user }}  group={{ application_user }} state=directory recurse=yes

   - name: Start hybris
     command:  chdir={{ application_home }}/hybris/hybris/bin/platform/ ./hybrisserver.sh {{ item }}
     with_items:
     - start
     sudo: true
     sudo_user: hybris

   - name: wait for hybris to start
     wait_for: host={{inventory_hostname}} port=9001
