---

   - name: Create Installer Directory
     file: path={{ installer_dir }}/deploy owner=hybris group=hybris mode=0755 state=directory

   - name: Download Tar for deployment
     get_url: url={{ jenkins_url }}/{{ build_num }} dest={{ installer_dir }}/deploy  mode=0755
     register: latestcode_result

   - name: Delete old app file
     command: chdir={{ installer_dir }}/deploy /usr/bin/rm -rf app
     when: latestcode_result.changed

   - name: Creating app folder again
     file: path={{ installer_dir }}/deploy/app owner=hybris group=hybris mode=0755 state=directory
     when: latestcode_result.changed

   - name: Extract Tar 
     command: chdir={{ installer_dir }}/deploy /usr/bin/tar -xvf {{ build_num }} -C app

   - name: Unzip Scripts 
     command: chdir={{ installer_dir }}/deploy/app /usr/bin/unzip -o {{ script_pkg }} 

   - name: Trigger Deployment
     shell: export APP_HYBRIS_HOME={{ APP_HYBRIS_HOME }} && chmod +x -R . && ./deploy.sh -task codeDeploy -env {{ environment }}  chdir={{ installer_dir }}/deploy/app/hybris/bnr/scripts/app-scripts/

#   - name: wait for hybris to start
     #wait_for: host={{inventory_hostname}} port=9001
