---

   - name: Setup | creating default user for solr
     command: useradd -m {{ solr_user }} creates=/home/{{ solr_user }}
     sudo: true

   - name: Create Installer Directory
     file: path={{ installer_dir }} owner=root group=root mode=0775  state=directory

   - name: Download java
     get_url: url={{ repo }}/Hybris/jdk-{{ java_version }}.zip dest={{ installer_dir }}  mode=0775
     register: java_result

   - name: Install Java
     command: chdir={{ installer_dir }} /usr/bin/unzip -o jdk-{{ java_version }}.zip -d {{ application_home }}
     when: java_result.changed

   - name: Symlink install directory jdk
     file: src={{ application_home }}/jdk-{{ java_version }} path={{ application_home }}/jdk state=link

   - name: Download Tomcat
     get_url: url={{ repo }}/Hybris/apache-tomcat-{{ tomcat_version }}.zip dest={{ installer_dir }}  mode=0440
     register: tomcat_result

   - name: Install Tomcat
     command: chdir={{ installer_dir }} /usr/bin/unzip -o apache-tomcat-{{ tomcat_version }}.zip -d {{ application_home }}
     when: tomcat_result.changed
     notify: restart solr

   - name: Symlink install directory tomcat
     file: src={{ application_home }}/apache-tomcat-{{ tomcat_version }} path={{ application_home }}/tomcat state=link

   - name: update server.xml
     template: src=server.xml.j2 dest={{ application_home }}/tomcat/conf/server.xml
     notify: restart solr

   - name: update init.script
     template: src=init.script.j2 dest={{ application_home }}/tomcat/bin/init-script.sh
     notify: restart solr

   - name: Download solr
     get_url: url={{ repo }}/Hybris/solr-{{ solr_version }}.zip dest={{ installer_dir }}  mode=0440
     register: solr_result

   - name: Install solr
     command: chdir={{ installer_dir }} /usr/bin/unzip -o solr-{{ solr_version }}.zip -d {{ application_home }}/tomcat/
     when: solr_result.changed
     notify: restart solr

   - name: Download solr lib
     get_url: url={{ repo }}/Hybris/solr-{{ solr_version }}-lib.zip dest={{ installer_dir }}  mode=0440
     register: solr_lib_result

   - name: Install solr lib
     command: chdir={{ installer_dir }} /usr/bin/unzip -o solr-{{ solr_version }}-lib.zip -d {{ application_home }}/tomcat/lib
     when: solr_lib_result.changed
     notify: restart solr

   - name: Copy solr.war 
     command: chdir={{ application_home }}/tomcat/ /usr/bin/cp -r solr/server/webapps/solr.war webapps/solr.war
     when: solr_result.changed
     notify: restart solr

   - name: Change ownership of Tomcat installation
     file: path={{ application_home }}/apache-tomcat-{{ tomcat_version }} owner={{ solr_user }}  group={{ solr_user }} state=directory recurse=yes

   - name: Change scripts permission
     file: dest={{ application_home }}/tomcat/bin/ state=directory mode=0775 recurse=yes owner={{ solr_user }}  group={{ solr_user }}

